EXPERIMENT.analysis.alpha = 0.05;
EXPERIMENT.analysis.sstype = 3;



EXPERIMENT.analysis.MD0.factors = {'Systems'};


EXPERIMENT.analysis.MD0.anova = @(data, factors) anovan(...
    data, {factors('Systems')}, ...
    'alpha', EXPERIMENT.analysis.alpha, ...
    'sstype', EXPERIMENT.analysis.sstype, ...
    'varnames', EXPERIMENT.analysis.MD0.factors, ...
    'display', 'off');


EXPERIMENT.analysis.MD1.factors = {'Topics', 'Systems'};


EXPERIMENT.analysis.MD1.anova = @(data, factors) anovan(...
    data, {factors('Topics'), factors('Systems')}, ...
    'alpha', EXPERIMENT.analysis.alpha, ...
    'sstype', EXPERIMENT.analysis.sstype, ...
    'varnames', EXPERIMENT.analysis.MD1.factors, ...
    'display', 'off');

EXPERIMENT.analysis.MD1nested.factors = {'Topics', 'Systems', 'Utterances'};


EXPERIMENT.analysis.MD1nested.anova = @(data, factors) anovan(...
    data, {factors('Topics'), factors('Systems'), factors('Utterances')},...
    'nested', [[0, 0, 0]; [0, 0, 0]; [0, 0, 0]], ...
    'alpha', EXPERIMENT.analysis.alpha, ...
    'sstype', EXPERIMENT.analysis.sstype, ...
    'varnames', EXPERIMENT.analysis.MD1nested.factors, ...
    'display', 'off');
%EXPERIMENT.analysis.anova.MD2 = @(data, topics, utterances, systems) anovan(...
%    data, {topics, utterances, systems}, ...
%    'alpha', EXPERIMENT.analysis.alpha, ...
%    'sstype', EXPERIMENT.analysis.sstype, ...
%    'nested', [[0, 0, 0]; [1, 0, 0]; [0, 0, 0]], ...
%    'varnames', {'Topics', 'utterances', 'Systems'}, ...
%    'display', 'off');


EXPERIMENT.analysis.MD2.factors = {'Topics', 'Systems', 'Alphas'};

EXPERIMENT.analysis.MD2.anova = @(data, factors) anovan(...
    data, {factors('Topics'), factors('Systems'), factors('Alphas')}, ...
    'alpha', EXPERIMENT.analysis.alpha, ...
    'sstype', EXPERIMENT.analysis.sstype, ...
    'varnames', EXPERIMENT.analysis.MD2.factors, ...
    'display', 'off');